kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
    - secrets
    providers:
    - aescbc:
        keys:
        - name: default
          secret: oYvf6V6BnUC4wh1CmJs7yeIBbIGjH9Od01zAOC7Abyo=
    - identity: {}
